name: ci
on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.c_compiler }}-${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-14]
        build_type: [Debug, Release]
        c_compiler: [gcc-13, gcc-14, clang-18]
        include:
          # ubuntu configurations
          - os: ubuntu-24.04
            c_compiler: gcc-13
            cpp_compiler: g++-13
          - os: ubuntu-24.04
            c_compiler: gcc-14
            cpp_compiler: g++-14
          - os: ubuntu-24.04
            c_compiler: clang-18
            cpp_compiler: clang++-18

          # macOS configurations
          - os: macos-14
            c_compiler: clang
            cpp_compiler: clang++

        exclude:
          # exclude gcc/clang-18 on macos (use Apple clang)
          - os: macos-14
            c_compiler: gcc-13
          - os: macos-14
            c_compiler: gcc-14
          - os: macos-14
            c_compiler: clang-18

    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: install compilers on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13 gcc-14 g++-14 clang-18

      - name: install htslib on ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libhts-dev

      - name: install htslib on macos
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install htslib

      - name: set reusable variables
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> $GITHUB_OUTPUT

      - name: configure cmake
        run: cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_CXX_STANDARD=20
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: build atroplex
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --parallel